# Generated by Django 2.1.4 on 2019-06-01 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='work',
            field=models.ForeignKey(db_column='work_id', on_delete=django.db.models.deletion.CASCADE, to='work.Work'),
        ),
    ]
