# Generated by Django 2.1.4 on 2019-06-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20190601_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='work',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
