# Generated by Django 2.1.4 on 2019-06-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='document',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
