# Generated by Django 2.1.4 on 2019-06-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_work_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='document',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
    ]
